# -*- coding: utf-8 -*-
"""NLP Project : Sentiment Analysis streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bzo4eNnn2M2GTwIBKDH8r_AtzoZbfSL7
"""

import pandas as pd
import re
import nltk

from nltk.corpus import stopwords
nltk.download('stopwords')

# a lil EDA 👀
train_df["emotion_name"].value_counts().plot(kind='bar')
plt.title("Emotion Distribution")
plt.show()

train_df["sentiment"].value_counts().plot(kind='bar')
plt.title("Sentiment Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Count")
plt.show()

train_df = pd.read_csv("/content/training.csv.xls")
val_df   = pd.read_csv("/content/validation.csv.xls")
test_df  = pd.read_csv("/content/test.csv.xls")

print(train_df.head())

mapping = {
    0: "sadness",
    1: "joy",
    2: "love",
    3: "anger",
    4: "fear",
    5: "surprise"
}

train_df["emotion_name"] = train_df["label"].map(mapping)
val_df["emotion_name"]   = val_df["label"].map(mapping)
test_df["emotion_name"]  = test_df["label"].map(mapping)

def emotion_to_sentiment(emotion):
    if emotion in ["joy", "love"]:
        return "positive"
    elif emotion in ["sadness", "anger", "fear"]:
        return "negative"
    else:
        return "neutral"

train_df["sentiment"] = train_df["emotion_name"].apply(emotion_to_sentiment)
val_df["sentiment"]   = val_df["emotion_name"].apply(emotion_to_sentiment)
test_df["sentiment"]  = test_df["emotion_name"].apply(emotion_to_sentiment)

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^\w\s]', '', text)

    words = text.split()
    words = [word for word in words if word not in stop_words]

    return " ".join(words)

train_df["clean_text"] = train_df["text"].apply(clean_text)
val_df["clean_text"]   = val_df["text"].apply(clean_text)
test_df["clean_text"]  = test_df["text"].apply(clean_text)

train_df.to_csv("train_cleaned.csv", index=False)
val_df.to_csv("val_cleaned.csv", index=False)
test_df.to_csv("test_cleaned.csv", index=False)

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2))

X_train = tfidf.fit_transform(train_df["clean_text"])
X_val   = tfidf.transform(val_df["clean_text"])

from sklearn.linear_model import LogisticRegression

emotion_model = LogisticRegression(max_iter=1000, class_weight='balanced')
emotion_model.fit(X_train, train_df["label"])

sentiment_model = LogisticRegression(max_iter=1000)
sentiment_model.fit(X_train, train_df["sentiment"])

from sklearn.metrics import accuracy_score, classification_report

# Transform validation text
X_val_tfidf = tfidf.transform(val_df["clean_text"])

# Predictions
y_pred_emo = emotion_model.predict(X_val_tfidf)
y_pred_sent = sentiment_model.predict(X_val_tfidf)

print("Emotion Accuracy:", accuracy_score(val_df["label"], y_pred_emo))
print("Sentiment Accuracy:", accuracy_score(val_df["sentiment"], y_pred_sent))

print("\nEmotion Report:\n")
print(classification_report(val_df["label"], y_pred_emo))

print("\nSentiment Report:\n")
print(classification_report(val_df["sentiment"], y_pred_sent))

# ===== MANUAL TESTING =====

# emotion mapping (for readable output)
emotion_map = {
    0: "sadness",
    1: "joy",
    2: "love",
    3: "anger",
    4: "fear",
    5: "surprise"
}

# take input
text = input("Enter a sentence: ")

# clean
clean = clean_text(text)

# vectorize
vec = tfidf.transform([clean])

# predict
emotion_pred = emotion_model.predict(vec)[0]
sentiment_pred = sentiment_model.predict(vec)[0]

# convert emotion number → name
emotion_name = emotion_map[emotion_pred]

# output
print("\n🔍 Result:")
print("Text:", text)
print("Emotion:", emotion_name)
print("Sentiment:", sentiment_pred)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(val_df["label"], y_pred_emo)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title("Emotion Confusion Matrix")
plt.show()

cm_sent = confusion_matrix(val_df["sentiment"], y_pred_sent)

disp = ConfusionMatrixDisplay(confusion_matrix=cm_sent)
disp.plot()
plt.title("Sentiment Confusion Matrix")
plt.show()

